config/routes.rb
Rails.application.routes.draw do  # The priority is based upon order of creation: first created -> highest priority.
  devise_for :users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)  
   root 'fonts#start'
   

     resources :fonts
     resources :categories

end

app/models/category.rb
class Category < ActiveRecord::Base
end

app/models/font.rb
class CreateFonts < ActiveRecord::Migration
  def change
    create_table :fonts do |t|
      t.string :name
      t.string :status

      t.timestamps null: false
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < InheritedResources::Base
  private
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/fonts_controller.rb
class FontsController < InheritedResources::Base

  private

    def font_params
      params.require(:font).permit(:name, :status)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/fonts_helper.rb
module FontsHelper
end

app/views/categories/_form.html.haml
= form_for @category do |f|
  - if @category.errors.any?
    #error_explanation
      %h2= "#{pluralize(@category.errors.count, "error")} prohibited this category from being saved:"
      %ul
        - @category.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .actions
    = f.submit 'Save'

app/views/categories/edit.html.haml
%h1 Editing category

= render 'form'

= link_to 'Show', @category
\|
= link_to 'Back', categories_path

app/views/categories/index.html.haml
%h1 Listing categories

%table
  %thead
    %tr
      %th Name
      %th
      %th
      %th

  %tbody
    - @categories.each do |category|
      %tr
        %td= category.name
        %td= link_to 'Show', category
        %td= link_to 'Edit', edit_category_path(category)
        %td= link_to 'Destroy', category, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Category', new_category_path

app/views/categories/new.html.haml
%h1 New category

= render 'form'

= link_to 'Back', categories_path

app/views/categories/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @category.name

= link_to 'Edit', edit_category_path(@category)
\|
= link_to 'Back', categories_path

app/views/fonts/_form.html.haml
= semantic_form_for @font do |f|
  = f.inputs do
    = f.input :name
    = f.input :status

  = f.actions do
    = f.action :submit, :as => :input

app/views/fonts/edit.html.haml
%h1 Editing font

= render 'form'

= link_to 'Show', @font
\|
= link_to 'Back', fonts_path

app/views/fonts/index.html.haml
%h1 Listing fonts

%table
  %thead
    %tr
      %th Name
      %th Status
      %th
      %th
      %th

  %tbody
    - @fonts.each do |font|
      %tr
        %td= font.name
        %td= font.status
        %td= link_to 'Show', font
        %td= link_to 'Edit', edit_font_path(font)
        %td= link_to 'Destroy', font, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Font', new_font_path

app/views/fonts/new.html.haml
%h1 New font

= render 'form'

= link_to 'Back', fonts_path

app/views/fonts/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @font.name
%p
  %b Status:
  = @font.status

= link_to 'Edit', edit_font_path(@font)
\|
= link_to 'Back', fonts_path

app/views/fonts/start.html.haml
%h3#12.asd<
  this summer you see this2

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Ffont
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = yield